version: 2

models:
  - name: dim_customer_recharge_lpc
    description: Each record is a unique customer
    columns:
      - name: customer_key
        description: Unique key for the table
        tests:
          - not_null
          - unique
