dbt_mcgee:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: eg99003.australia-east.azure

      # User/password auth
      user: dbt
      password: $9kLp*1xW@Bz3T!q
      role: ACCOUNTADMIN
      database: SWOOP_QUERIES
      warehouse: COMPUTE_WH
      schema: transformed
      threads: 4
      client_session_keep_alive: False
      query_tag: lenin