select
    id,
    update_time::date as update_time,
    creator_user_id,
    user_id,
    person_id,
    pipeline_id,
    org_id,
    stage_id,
    currency,
    title,
    value,
    stage_change_time::date as stage_change_time,
    deleted,
    status,
    probability,
    lost_reason,
    visible_to,
    close_time::date as close_time,
    won_time::date as won_time,
    first_won_time::date as first_won_time,
    lost_time::date as lost_time,
    expected_close_date::date as expected_invoice_date,
    last_incoming_mail_time,
    last_outgoing_mail_time,
    label,
    stage_order_nr,
    formatted_value,
    weighted_value,
    formatted_weighted_value,
    weighted_value_currency,
    rotten_time,
    cc_email,
    org_hidden,
    person_hidden,
    created_at::date as created_at,
    active,
    custom_subscription_period::date as subscription_start_date,
    custom_end_date_of_subscription_period::date as subscription_end_date
from {{ source("pipedrive", "deal_history") }}
where _fivetran_active
