version: 2

models:
  - name: stg_inventory_item_level_tenkara_usa
    columns:
      - name: inventory_item_level_key
        tests:
          - not_null
          - unique      

  - name: dim_product_tenkara_usa
    columns:
      - name: product_key
        description: Unique key for the table
        tests:
          - unique
          - not_null

  - name: fact_order_line_item_tenkara_usa
    columns:
      - name: order_line_item_id
        description: Unique key for the table
        tests:
          - unique
          - not_null
      - name: product_key
        description: Unique key for the table
        tests:
          - not_null
      - name: date_key
        description: Unique key for the table
        tests:
          - not_null

  - name: base_rpt_customers_tenkara_usa
    description: "."
    columns:
      - name: customer_key
        description: Unique identifier
        tests:
          - not_null
          - unique

  - name: base_rpt_product_tenkara_usa
    description: "."
    columns:
      - name: product_key
        description: Unique identifier
        tests:
          - not_null
          - unique
    
  - name: base_rpt_order_tenkara_usa
    description: "."
    columns:
      - name: order_id
        description: Unique identifier
        tests:
          - not_null
          - unique          

  - name: base_rpt_order_line_item_tenkara_usa
    description: "."
    columns:
      - name: order_line_item_id
        description: Unique identifier
        tests:
          - not_null
          - unique                   