version: 2

models:
  - name: stg_order_montem
    description: Each record is a version of customer address.
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customer_montem')
              field: id