SELECT ADDRESS_1,
    ID,
    ZIP,
    ADDRESS_2,
    CITY,
    NAME,
    PROVINCE,
    COMPANY,
    COUNTRY,
    CUSTOMER_ID,
    PHONE,
    FIRST_NAME,
    LONGITUDE,
    COUNTRY_CODE,
    IS_DEFAULT,
    LATITUDE,
    PROVINCE_CODE,
    LAST_NAME,
    ROW_NUMBER() over (partition by customer_id order by id desc) as latest_entry
FROM {{source("SHOPIFY_AMERICAN_DUCHESS", "CUSTOMER_ADDRESS")}}