select
    verified_email,
    first_name,
    metafield,
    _fivetran_synced,
    lifetime_duration,
    orders_count,
    last_name,
    accepts_marketing_updated_at,
    email,
    phone,
    email_marketing_consent_state,
    id,
    {{ dbt_utils.surrogate_key(['id']) }} as customer_key,
    updated_at,
    created_at,
    tax_exempt,
    accepts_marketing,
    currency,
    marketing_opt_in_level,
    multipass_identifier,
    can_delete,
    email_marketing_consent_consent_updated_at,
    email_marketing_consent_opt_in_level,
    note,
    state,
    total_spent
from {{ source("SHOPIFY_AMERICAN_DUCHESS", "CUSTOMER") }}
where not _fivetran_deleted
