select 
    id,
    customer_id,
    address_1,
    zip,
    address_2,
    city,
    name,
    province,
    company,
    country,
    phone,
    first_name,
    longitude,
    country_code,
    is_default,
    latitude,
    province_code,
    last_name,
    row_number() over (partition by customer_id order by id desc) as latest_entry
from {{source('shopify_tenkara_usa', 'customer_address')}}