select
    {{ dbt_utils.surrogate_key(['id']) }} as customer_key,
    id,
    first_name,
    last_name,
    verified_email,
    email,
    phone,
    state,
    currency,
    total_spent,
    lifetime_duration,
    orders_count,
    tax_exempt,
    marketing_opt_in_level,
    multipass_identifier,
    can_delete,
    metafield,
    accepts_marketing,
    accepts_marketing_updated_at,
    email_marketing_consent_state,
    email_marketing_consent_consent_updated_at,
    email_marketing_consent_opt_in_level,
    note,
    updated_at,
    created_at,
    _fivetran_synced
from {{source('shopify_tenkara_usa', 'customer')}}
where not _fivetran_deleted