SELECT 
    DEPARTMENT,
    EMPLOYEE_NAME,
    EMPLOYMENT_TYPE,
    REGION,
    ANNUAL_COST,
    PAYROLL_REGION,
    ROLE,
    ESTIMATE_CAC_,
    ACCOUNT_ID,
    CASE 
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'JAN' THEN '01'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'FEB' THEN '02'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'MAR' THEN '03'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'APR' THEN '04'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'MAY' THEN '05'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'JUN' THEN '06'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'JUL' THEN '07'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'AUG' THEN '08'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'SEP' THEN '09'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'OCT' THEN '10'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'NOV' THEN '11'
        WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'DEC' THEN '12'
    END AS MONTH,
    '20' || SUBSTR(MONTH_YEAR, 5, 2) AS YEAR,
    TO_DATE(CONCAT('20', SUBSTR(MONTH_YEAR, 5, 2), '-', 
        CASE 
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'JAN' THEN '01'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'FEB' THEN '02'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'MAR' THEN '03'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'APR' THEN '04'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'MAY' THEN '05'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'JUN' THEN '06'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'JUL' THEN '07'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'AUG' THEN '08'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'SEP' THEN '09'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'OCT' THEN '10'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'NOV' THEN '11'
            WHEN SUBSTR(MONTH_YEAR, 1, 3) = 'DEC' THEN '12'
        END, '-01'), 'YYYY-MM-DD') AS MONTH_YEAR_DATE,
    AMOUNT
FROM {{ source("google_sheets", "salary_forecast") }}
UNPIVOT (
    AMOUNT FOR MONTH_YEAR IN (
        JAN_24, FEB_24, MAR_24, APR_24, MAY_24, JUN_24, JUL_24, AUG_24, SEP_24, OCT_24, NOV_24, DEC_24,
        JAN_25, FEB_25, MAR_25, APR_25, MAY_25, JUN_25, JUL_25,
        JUL_23, AUG_23, SEP_23, OCT_23, NOV_23, DEC_23
    )
) AS UNPVT