version: 2

sources:
  - name: google_sheets
    database: swoop_database  
    schema: swoop_sharepoint  
    tables:
      - name: customer_metadata_sheet_1
      - name: salary_forecast_sheet_1
      - name: salary_forecast
        identifier: salary_forecast_salary_forecast
      - name: overhead_forecast
        identifier: overhead_forecast_forecast