version: 2

sources:
  - name: xero
    database: swoop_database  
    schema: swoop_xero  
    tables:
      - name: journal_line
      - name: journal
      - name: journal_line_has_tracking_category
      - name: tracking_category_has_option
      - name: tracking_category_option
      - name: tracking_category
      - name: invoice
      - name: account
  - name: xero_gs
    database: swoop_database  
    schema: swoop_googlesheets  
    tables:
      - name: payroll_regions
  - name: xero_sp
    database: swoop_database  
    schema: swoop_sharepoint  
    tables:
      - name: customer_metadata_sheet_1
      - name: salary_forecast_salary_forecast
      - name: swoop_coa_metadata
        identifier: COA_METADATA_COA_METADATA
      - name: coa_metadata
        identifier: COA_METADATA_COA_METADATA
        