version: 2

models:
  - name: stg_customer_address_lpc
    description: Each record is a version of customer address.
    columns:
      - name: customer_address_id
        description: Unique key for the table
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customer_lpc')
              field: customer_id

  - name: stg_inventory_item_level_lpc
    columns:
      - name: inventory_item_id
        tests:
          - not_null
          - unique

  - name: stg_order_lpc
    description: Each record represents an order in Shopify.
    columns:
      - name: currency
        description: The three-letter code for the shop currency.
        tests:
          - accepted_values:
              values: ['USD']        
      - name: order_id
        description: The ID of the order, used for API purposes. This is different from the order_number property, which is the ID used by the shop owner and customer.
        tests:
          - not_null
          - unique

  - name: stg_product_lpc
    description: Each record represents a product in Shopify.
    columns:
      - name: product_id
        description: An unsigned 64-bit integer that's used as a unique identifier for the product. Each id is unique across the Shopify system. No two products will have the same id, even if they're from different shops.
        tests:
          - not_null
          - unique

  - name: stg_product_variant_lpc
    description: Each record represents a product variant in Shopify
    columns:
      - name: product_variant_id
        description: The unique numeric identifier for the product variant.
        tests:
          - not_null
          - unique
      - name: product_id
        description: The unique numeric identifier for the product.
        tests:
          - not_null
          - relationships:
              to: ref('stg_product_lpc')
              field: product_id        
      - name: inventory_item_id
        description: The unique identifier for the inventory item, which is used in the Inventory API to query for inventory information.
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_inventory_item_level_lpc')
              field: inventory_item_id            

  - name: stg_order_line_item_lpc
    description: Each record represents a line item from an order in Shopify.
    columns:
      - name: order_line_item_id
        description: The ID of the line item.
        tests:
          - not_null
          - unique
      - name: order_id
        description: The ID of the related order.
        tests:
          - not_null       
      - name: product_variant_name
        description: The name of the product variant.
        tests:
          - not_null       
      - name: product_title
        description: The title of the product.
        tests:
          - not_null