{{ config(alias="dim_orders") }}

select id,
        {{ dbt_utils.surrogate_key(['id']) }} as order_key,
        insurance,
        fulfillment_status,
        has_dry_ice,
        order_number,
        priority_flag,
        saturday_delivery,
        source,
        allow_partial,
        total_discounts,
        adult_signature_required,
        packing_note,
        flagged,
        legacy_id,
        currency,
        email,
        alcohol,
        expected_weight_in_oz,
        required_ship_date,
        total_price,
        require_signature,
        profile,
        allocation_priority,
        allow_split,
        shop_name,
        total_tax,
        gift_invoice,
        order_date,
        account_id,
        insurance_amount,
        subtotal,
        _fivetran_synced,
        line_items,
        third_party_shipper,
        order_history,
        product_sku
from {{ref('stg_shiphero_orders')}}