select
    id as order_line_item_id,
    order_id,
    variant_id as product_variant_id,
    product_id,
    lower(variant_title) as product_variant_title,
    lower(name) as product_variant_name,
    lower(title) as product_title,
    index as order_line_index,
    price,
    quantity,
    price_set,
    pre_tax_price,
    pre_tax_price_set,
    nullif(lower(sku), '') as sku,
    total_discount,
    total_discount_set,
    destination_location_address_2,
    fulfillable_quantity,
    fulfillment_status,
    fulfillment_service,
    origin_location_address_2,
    origin_location_city,
    requires_shipping as is_shipping_required,
    origin_location_id,
    destination_location_id,
    origin_location_address_1,
    origin_location_country_code,
    destination_location_country_code,
    destination_location_name,
    destination_location_zip,
    properties,
    product_exists,
    lower(vendor) as vendor,
    case 
        when nvl(lower(vendor), '') != 'route' then FALSE
        when nvl(lower(vendor), '') = 'route' then TRUE
        else NULL
    end as is_vendor_route,
    grams,
    origin_location_name,
    taxable as is_taxable,
    variant_inventory_management,
    origin_location_zip,
    destination_location_address_1,
    destination_location_city,
    destination_location_province_code,
    gift_card as is_gift_card,
    origin_location_province_code,
    tax_code,
    _fivetran_synced
    
from {{ source('shopify_alice_ames', 'order_line') }}
