version: 2

sources:
  - name: impress
    database: IMPRESS_DATABASE
    schema: IMPRESS_XERO 
    tables:
      - name: journal_line
      - name: journal
      - name: journal_line_has_tracking_category
      - name: tracking_category_has_option
      - name: tracking_category_option
      - name: tracking_category
      - name: invoice
      - name: account

  - name: impress_sp
    database: impress_database
    schema: impress_share_point  
    tables:
      - name: coa_metadata


  - name: pearshop
    database: impress_database    
    schema: pearshop_xero  
    tables:
      - name: journal_line
      - name: journal
      - name: journal_line_has_tracking_category
      - name: tracking_category_has_option
      - name: tracking_category_option
      - name: tracking_category
      - name: invoice
      - name: account


##combined
  - name: combined_forecast
    database: impress_database
    schema: impress_share_point
    tables:
      - name: forecast_snowflake_combined_forecast


##financials impress
  - name: impress_new
    database: impress_queries
    schema: transformed
    tables: 
      - name: financials_impress_new

