version: 2

sources:
  - name: impress
    database: impress_database    
    schema: impress_xero  
    tables:
      - name: journal_line
      - name: journal
      - name: journal_line_has_tracking_category
      - name: tracking_category_has_option
      - name: tracking_category_option
      - name: tracking_category
      - name: invoice
      - name : account

  # - name: polymer_gs
  #   database: swoop_database  
  #   schema: swoop_googlesheets  
  #   tables:
  #     - name: payroll_regions
  - name: sp_impress
    database: impress_database  
    schema: impress_share_point  
    tables:
      - name: coa_metadata
        identifier: coa_metadata
      - name: forecast_snowflake_combined_forecast


##pearshop
  - name: pearshop
    database: impress_database    
    schema: pearshop_xero  
    tables:
      - name: journal_line
      - name: journal
      - name: journal_line_has_tracking_category
      - name: tracking_category_has_option
      - name: tracking_category_option
      - name: tracking_category
      - name: invoice
      - name: account

