select
{{ dbt_utils.surrogate_key(['ol.ORDER_LINE_ITEM_ID']) }} as ORDER_LINE_ITEM_KEY,
ol.ORDER_ID as ORDER_ID,
ol.ORDER_LINE_ITEM_ID as ORDER_LINE_ITEM_ID,
ol.TOTAL_WEIGHT as TOTAL_WEIGHT,
ol.LINE_ITEM_WEIGHT as LINE_ITEM_WEIGHT,
ol.ORDER_LINE_ITEM_PRICE as ORDER_LINE_ITEM_PRICE,
ol.TAXES_INCLUDED as TAXES_INCLUDED,
ol.CURRENCY as CURRENCY,
ol.ORDER_NUMBER as ORDER_NUMBER,
ol.REQUIRES_SHIPPING as REQUIRES_SHIPPING,
ol.IS_GIFT_CARD_USED as IS_GIFT_CARD_USED,
ol.ORDER_CREATED_TS as ORDER_CREATED_TS,
ol.ORDER_DISCOUNT_CODE as ORDER_DISCOUNT_CODE,
ol.ORDER_LINE_ITEM_PRE_TAX_PRICE as ORDER_LINE_ITEM_PRE_TAX_PRICE
from {{ ref('stg_holding_table') }} ol