select
{{ dbt_utils.surrogate_key(['ol.ID']) }} as ORDER_LINE_ITEM_KEY,
o.ID as ORDER_ID,
ol.ID as ORDER_LINE_ITEM_ID,
ol.GRAMS AS LINE_ITEM_WEIGHT,
ol.PRICE as ORDER_LINE_ITEM_PRICE,
o.TAXES_INCLUDED as TAXES_INCLUDED,
NULLIF(TRIM(o.CURRENCY),'') as CURRENCY,
o.ORDER_NUMBER as ORDER_NUMBER,
ol.REQUIRES_SHIPPING as REQUIRES_SHIPPING,
ol.GIFT_CARD as IS_GIFT_CARD_USED,
o.CREATED_AT as ORDER_CREATED_TS,
ol.PRE_TAX_PRICE as ORDER_LINE_ITEM_PRE_TAX_PRICE
from {{ source('ALICE_AMES_SHOPIFY', 'ORDER_LINE') }} ol left join {{ source('ALICE_AMES_SHOPIFY', 'ORDER') }} o  on o.ID = ol.ORDER_ID