select 
{{ dbt_utils.surrogate_key(['dc.CODE','pr.ID']) }} as DISCOUNT_KEY,
dc.CODE as DISCOUNT_CODE,
pr.ID as PRICE_RULE_ID,
pr.CREATED_AT as CREATED_AT,
pr.STARTS_AT as STARTS_AT,
pr.ENDS_AT as ENDS_AT,
pr.TITLE as DISCOUNT_TARGET_TYPE,
pr.TARGET_SELECTION as DISCOUNT_ALLOCATION_METHOD,
pr.ALLOCATION_METHOD as DISCOUNT_VALUE_TYPE,
pr.VALUE_TYPE as DISCOUNT_VALUE,
'SHOPIFY' as CHANNEL_SOURCE
from "AESTUARY_RAW"."SHOPIFY"."DISCOUNT_CODE" dc inner join "AESTUARY_RAW"."SHOPIFY"."PRICE_RULE" pr on dc.PRICE_RULE_ID = pr.ID