select
{{ dbt_utils.surrogate_key(['p.ID', 'pv.ID','pt.INDEX']) }} as PRODUCT_KEY,
p.ID as PRODUCT_ID,
p.TITLE as PRODUCT_TITLE,
p.HANDLE as PRODUCT_HANDLE,
PRODUCT_TYPE as PRODUCT_TYPE,
STATUS as PRODUCT_STATUS,
pt.VALUE as PRODUCT_STYLE,
pt.INDEX as PRODUCT_TAG_INDEX,
pt.VALUE as PRODUCT_TAG_VALUE,
pv.ID as PRODUCT_VARIANT_ID,
pv.TITLE as PRODUCT_VARIANT_TITLE,
pv.PRICE as PRODUCT_PRICE,
pv.SKU as PRODUCT_SKU,
pv.POSITION as PRODUCT_VARIANT_POSITION,
pv.CREATED_AT as CREATED_AT,
pv.UPDATED_AT as UPDATED_AT,
pv.BARCODE as PRODUCT_BARCODE,
pv.GRAMS as PRODUCT_GRAMS,
pv.WEIGHT as PRODUCT_WEIGHT,
pv.WEIGHT_UNIT as PRODUCT_WEIGHT_UNIT
from "AESTUARY_RAW"."SHOPIFY"."PRODUCT" p left join "AESTUARY_RAW"."SHOPIFY"."PRODUCT_VARIANT" pv on p.ID = pv.PRODUCT_ID
left join "AESTUARY_RAW"."SHOPIFY"."PRODUCT_TAG" pt on p.ID = pt.PRODUCT_ID
