select
{{ dbt_utils.surrogate_key(['p.ID', 'pv.ID','pt.INDEX']) }} as PRODUCT_KEY,
p.ID as PRODUCT_ID,
NULLIF(TRIM(p.TITLE),'') as PRODUCT_TITLE,
NULLIF(TRIM(p.HANDLE),'') as PRODUCT_HANDLE,
NULLIF(TRIM(PRODUCT_TYPE),'') as PRODUCT_TYPE,
NULLIF(TRIM(STATUS),'') as PRODUCT_STATUS,
NULLIF(TRIM(pt.VALUE),'') as PRODUCT_STYLE,
pt.INDEX as PRODUCT_TAG_INDEX,
NULLIF(TRIM(pt.VALUE),'') as PRODUCT_TAG_VALUE,
pv.ID as PRODUCT_VARIANT_ID,
NULLIF(TRIM(pv.TITLE),'') as PRODUCT_VARIANT_TITLE,
pv.PRICE as PRODUCT_PRICE,
NULLIF(TRIM(pv.SKU),'') as PRODUCT_SKU,
pv.POSITION as PRODUCT_VARIANT_POSITION,
pv.CREATED_AT as PRODUCT_CREATED_DATE,
pv.UPDATED_AT as PRODUCT_UPDATED_DATE,
NULLIF(TRIM(pv.BARCODE),'') as PRODUCT_BARCODE,
pv.GRAMS as PRODUCT_GRAMS,
pv.WEIGHT as PRODUCT_WEIGHT,
NULLIF(TRIM(pv.WEIGHT_UNIT),'') as PRODUCT_WEIGHT_UNIT
from {{ ref('product_snapshot') }} p left join {{ ref('product_variant_snapshot') }} pv on p.ID = pv.ID 
left join {{ source('ALICE_AMES_SHOPIFY', 'PRODUCT_TAG') }} pt on p.ID = pt.PRODUCT_ID
where p.DBT_VALID_TO is NULL and pv.DBT_VALID_TO is NULL
